version: 2
jobs:
   build:
     working_directory: /go/src/github.com/itzg/embd-controller-ssd1306
     docker:
       - image: circleci/golang:1.9
     steps:
       - checkout
       - run: curl https://glide.sh/get | sh
       - run: glide install
       - run: go test ./...